##
## Settings file.
##
PARALLEL_THREADS_NUM = 1000
TRACKER_THREAD_TIMEOUT = 5

TRACKERS_REFRESH_INTERVAL = 300

STORAGE_TYPE = 'mongodb'
STORAGE_HOST = 'redmine'
STORAGE_PORT = 27017
STORAGE_DB_NAME = 'tracking'

BACKDOOR_HOST = '127.0.0.1'
BACKDOOR_PORT = 8091
