##
## Settings file.
##
PARALLEL_THREADS_NUM = 1000
TRACKERS_REFRESH_INTERVAL = 300
TRACKER_THREAD_TIMEOUT = 5

STORAGE_TYPE = 'mongodb'
STORAGE_HOST = 'localhost'
STORAGE_PORT = 27017
STORAGE_DB_NAME = 'tracking'
